server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index inicio.html index.html;

    gzip on;
    gzip_types text/css application/javascript image/svg+xml application/json;

    location / {
        try_files $uri $uri/ =404;
        add_header Cache-Control "no-cache";
    }

    location ~* \.(js|css)$ {
        expires 0;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    location ~* \.(png|jpe?g|svg|ico|woff2?)$ {
        expires 7d;
        add_header Cache-Control "public";
    }
}